// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: protos/levels/levels.proto

package levels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LevelType int32

const (
	LevelType_Empty     LevelType = 0
	LevelType_XP        LevelType = 1
	LevelType_Milestone LevelType = 2
)

// Enum value maps for LevelType.
var (
	LevelType_name = map[int32]string{
		0: "Empty",
		1: "XP",
		2: "Milestone",
	}
	LevelType_value = map[string]int32{
		"Empty":     0,
		"XP":        1,
		"Milestone": 2,
	}
)

func (x LevelType) Enum() *LevelType {
	p := new(LevelType)
	*p = x
	return p
}

func (x LevelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LevelType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_levels_levels_proto_enumTypes[0].Descriptor()
}

func (LevelType) Type() protoreflect.EnumType {
	return &file_protos_levels_levels_proto_enumTypes[0]
}

func (x LevelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LevelType.Descriptor instead.
func (LevelType) EnumDescriptor() ([]byte, []int) {
	return file_protos_levels_levels_proto_rawDescGZIP(), []int{0}
}

type Level struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string    `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CharacterName string    `protobuf:"bytes,2,opt,name=CharacterName,proto3" json:"CharacterName,omitempty"`
	LevelType     LevelType `protobuf:"varint,3,opt,name=LevelType,proto3,enum=levels.LevelType" json:"LevelType,omitempty"`
	Experience    *int32    `protobuf:"varint,4,opt,name=Experience,proto3,oneof" json:"Experience,omitempty"`
	Levels        *int32    `protobuf:"varint,5,opt,name=Levels,proto3,oneof" json:"Levels,omitempty"`
}

func (x *Level) Reset() {
	*x = Level{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_levels_levels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level) ProtoMessage() {}

func (x *Level) ProtoReflect() protoreflect.Message {
	mi := &file_protos_levels_levels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level.ProtoReflect.Descriptor instead.
func (*Level) Descriptor() ([]byte, []int) {
	return file_protos_levels_levels_proto_rawDescGZIP(), []int{0}
}

func (x *Level) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Level) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *Level) GetLevelType() LevelType {
	if x != nil {
		return x.LevelType
	}
	return LevelType_Empty
}

func (x *Level) GetExperience() int32 {
	if x != nil && x.Experience != nil {
		return *x.Experience
	}
	return 0
}

func (x *Level) GetLevels() int32 {
	if x != nil && x.Levels != nil {
		return *x.Levels
	}
	return 0
}

var File_protos_levels_levels_proto protoreflect.FileDescriptor

var file_protos_levels_levels_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x2f,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x73, 0x22, 0xca, 0x01, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x24,
	0x0a, 0x0d, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x09, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73,
	0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x45, 0x78, 0x70,
	0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x06, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x45, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x73, 0x2a, 0x2d, 0x0a, 0x09, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x58, 0x50, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x10, 0x02,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x70, 0x75, 0x73, 0x74, 0x65, 0x6a, 0x6f, 0x76, 0x73, 0x6b, 0x79, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_levels_levels_proto_rawDescOnce sync.Once
	file_protos_levels_levels_proto_rawDescData = file_protos_levels_levels_proto_rawDesc
)

func file_protos_levels_levels_proto_rawDescGZIP() []byte {
	file_protos_levels_levels_proto_rawDescOnce.Do(func() {
		file_protos_levels_levels_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_levels_levels_proto_rawDescData)
	})
	return file_protos_levels_levels_proto_rawDescData
}

var file_protos_levels_levels_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_levels_levels_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_levels_levels_proto_goTypes = []interface{}{
	(LevelType)(0), // 0: levels.LevelType
	(*Level)(nil),  // 1: levels.Level
}
var file_protos_levels_levels_proto_depIdxs = []int32{
	0, // 0: levels.Level.LevelType:type_name -> levels.LevelType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_levels_levels_proto_init() }
func file_protos_levels_levels_proto_init() {
	if File_protos_levels_levels_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_levels_levels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Level); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_levels_levels_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_levels_levels_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_levels_levels_proto_goTypes,
		DependencyIndexes: file_protos_levels_levels_proto_depIdxs,
		EnumInfos:         file_protos_levels_levels_proto_enumTypes,
		MessageInfos:      file_protos_levels_levels_proto_msgTypes,
	}.Build()
	File_protos_levels_levels_proto = out.File
	file_protos_levels_levels_proto_rawDesc = nil
	file_protos_levels_levels_proto_goTypes = nil
	file_protos_levels_levels_proto_depIdxs = nil
}
